name: quiz_mater_apllication
description: "Quiz Master - Ứng dụng luyện thi trắc nghiệm THPT"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^4.11.0 
  firebase_auth: ^6.5.1 
  cloud_firestore: 
  firebase_storage: 
  cloud_functions: 

  # Kiến trúc
  flutter_bloc: 
  go_router: ^17.2.3
  get_it: ^8.0.3
  dartz: ^0.10.1
  equatable: ^2.0.8

  # Giao diện
  # google_fonts: ^8.1.0
  flutter_math_fork: ^0.7.4
  fl_chart: ^0.70.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_native_splash: 

  # Tiện ích
  flutter_dotenv: ^6.0.1
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_svg: ^2.3.0
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.6
  google_fonts: ^8.1.0
  image_picker: ^1.2.2
  firebase_ai: ^3.13.1

dev_dependencies:
  flutter_math_fork: ^0.7.4
  fl_chart: ^0.70.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: 
  mocktail: ^1.0.4
  flutter_launcher_icons: 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/quiz_master_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/quiz_master_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
