// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzlNPspidmnfh4jfGHpXQ-1iNQCD1gNv4',
    appId: '1:795544707095:web:7b736601f74b427065fc52',
    messagingSenderId: '795544707095',
    projectId: 'book-shop-791d3',
    authDomain: 'book-shop-791d3.firebaseapp.com',
    storageBucket: 'book-shop-791d3.firebasestorage.app',
    measurementId: 'G-XQHLK26M8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZFdpm7z5yR1g7dHtvR5vOCludeKJVhM',
    appId: '1:795544707095:android:1358659432eb837565fc52',
    messagingSenderId: '795544707095',
    projectId: 'book-shop-791d3',
    storageBucket: 'book-shop-791d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy3L8avag791s1qoSrsZtArCXsie3rbk4',
    appId: '1:795544707095:ios:d2658e3aec20279a65fc52',
    messagingSenderId: '795544707095',
    projectId: 'book-shop-791d3',
    storageBucket: 'book-shop-791d3.firebasestorage.app',
    iosBundleId: 'com.example.quizMaterApllication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy3L8avag791s1qoSrsZtArCXsie3rbk4',
    appId: '1:795544707095:ios:d2658e3aec20279a65fc52',
    messagingSenderId: '795544707095',
    projectId: 'book-shop-791d3',
    storageBucket: 'book-shop-791d3.firebasestorage.app',
    iosBundleId: 'com.example.quizMaterApllication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANyfx6bMyOAXcVrMbHuu9KQm4LqLiwdEI',
    appId: '1:795544707095:web:6379fadaa7920ad265fc52',
    messagingSenderId: '795544707095',
    projectId: 'book-shop-791d3',
    authDomain: 'book-shop-791d3.firebaseapp.com',
    storageBucket: 'book-shop-791d3.firebasestorage.app',
    measurementId: 'G-ZSXMYG9MKM',
  );
}
